<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Course;
use App\Models\CourseSection;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 1. Ensure Instructor exists
        $instructor = User::where('role', 'instructor')->first();
        if (!$instructor) {
            $this->command->error('No instructor found! Please run UserSeeder or create one first.');
            return;
        }

        // 2. Create Dummy Course
        $course = Course::create([
            'instructor_id' => $instructor->id,
            'title' => 'Automated Test Course ' . rand(100, 999),
            'description' => 'This course was generated by the CourseSeeder for Phase 7.5 testing.',
            'duration_hours' => 10, // Default duration
        ]);

        $this->command->info("Created Course: {$course->title}");

        // 3. Define Source Files (You must place these manually!)
        // Location: storage/app/seed_content/
        $sourceDir = storage_path('app/seed_content');
        $videoSource = $sourceDir . '/sample.mp4';
        $pdfSource = $sourceDir . '/sample.pdf';

        if (!File::exists($sourceDir)) {
            File::makeDirectory($sourceDir);
            $this->command->warn("Created directory: {$sourceDir}");
            $this->command->warn("Please place 'sample.mp4' and 'sample.pdf' there to use file copying!");
        }

        // 4. Create Sections
        $sections = [
            ['title' => 'Welcome Video', 'type' => 'video', 'src' => $videoSource, 'ext' => 'mp4'],
            ['title' => 'Course Syllabus', 'type' => 'document', 'src' => $pdfSource, 'ext' => 'pdf'],
            ['title' => 'Safety Protocol', 'type' => 'reading', 'src' => null, 'content' => "Always wear a helmet.\n\nThat is all."],
            ['title' => 'Lecture 1: Basics', 'type' => 'video', 'src' => $videoSource, 'ext' => 'mp4'],
            ['title' => 'Lecture 2: Advanced', 'type' => 'video', 'src' => $videoSource, 'ext' => 'mp4'],
        ];

        foreach ($sections as $index => $data) {
            $contentPath = null;
            $originalFilename = null;

            if ($data['type'] === 'reading') {
                $contentPath = $data['content'];
            } else {
                // Handle File Copy
                if (File::exists($data['src'])) {
                    $fileName = 'seeded_' . uniqid() . '.' . $data['ext'];
                    $destPath = 'course_content/' . $fileName; // Relative to public disk
                    
                    // Copy file to storage/app/public/course_content
                    Storage::disk('public')->put($destPath, File::get($data['src']));
                    
                    $contentPath = $destPath;
                    $originalFilename = basename($data['src']);
                } else {
                    $this->command->warn("Missing source file for {$data['title']}. Skipping file content.");
                    $contentPath = 'missing_file_placeholder.' . $data['ext'];
                    $originalFilename = 'missing_sample.' . $data['ext'];
                }
            }

            CourseSection::create([
                'course_id' => $course->id,
                'title' => $data['title'],
                'type' => $data['type'],
                'content' => $contentPath,
                'original_filename' => $originalFilename,
                'order' => $index + 1,
                'is_locked' => true, // Default to locked
                'is_skippable' => ($index % 2 == 0), // Alternate skippable
            ]);
        }

        $this->command->info("Seeded 5 sections for course ID: {$course->id}");
    }
}
